# MinIO Tenant の ArgoCD Application 設定
# S3 互換オブジェクトストレージクラスターのインスタンス
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
  annotations:
    # MinIO Operator がデプロイされた後にテナントをデプロイ
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    # リソースのクリーンアップを確実に行うためのファイナライザー
    - resources-finalizer.argocd.argoproj.io
spec:
  # ArgoCD プロジェクト設定
  project: default
  
  # Helm チャートのソース設定
  source:
    repoURL: https://operator.min.io/  # MinIO 公式 Tenant Helm リポジトリ
    chart: tenant
    targetRevision: 7.0.1  # 使用する MinIO Tenant チャートのバージョン

  # デプロイ先の設定
  destination:
    server: "https://kubernetes.default.svc"  # ローカル Kubernetes クラスター
    namespace: minio-tenant
  
  # 同期設定
  syncPolicy:
    syncOptions:
      # Namespace が存在しない場合は自動作成
      - CreateNamespace=true
