# Rook Ceph Operator の ArgoCD Application 設定
# Kubernetes 上で Ceph ストレージクラスターを管理するオペレーター
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
  annotations:
    # 依存関係のあるアプリケーションより先にデプロイされるように設定
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    # リソースのクリーンアップを確実に行うためのファイナライザー
    - resources-finalizer.argocd.argoproj.io
spec:
  # ArgoCD プロジェクト設定
  project: default
  
  # Helm チャートのソース設定
  source:
    repoURL: https://charts.rook.io/release  # Rook 公式 Helm リポジトリ
    chart: rook-ceph
    targetRevision: v1.16.5  # 使用する Rook Ceph オペレーターのバージョン
    
    helm:
      parameters:
        # k0s 環境向けの kubelet ディレクトリパス設定
        - name: csi.kubeletDirPath
          value: /var/lib/k0s/kubelet

  # デプロイ先の設定
  destination:
    server: "https://kubernetes.default.svc"  # ローカル Kubernetes クラスター
    namespace: rook-ceph
  
  # 同期設定
  syncPolicy:
    syncOptions:
      # Namespace が存在しない場合は自動作成
      - CreateNamespace=true
