apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    chart: promtail
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.16.6
    helm:
      values: |
        # Promtail設定
        config:
          # Lokiクライアント設定
          clients:
            - url: http://loki.observability.svc.cluster.local:3100/loki/api/v1/push
              tenant_id: ""
          
          # ポジションファイル（どこまで読んだか記録）
          # /run/promtail はHelmチャートでemptyDirとしてマウント済み
          positions:
            filename: /run/promtail/positions.yaml
          
          # Kubernetesからのログ収集設定
          scrape_configs:
            # Kubernetesポッドログ
            - job_name: kubernetes-pods
              kubernetes_sd_configs:
                - role: pod
              
              # パイプライン処理
              pipeline_stages:
                # Dockerログフォーマットをパース
                - docker: {}
                
                # TraceIDを抽出してラベル化（Tempoとの連携用）
                - regex:
                    expression: '(?:trace_id|traceID)[=:]?\s*([0-9a-fA-F]{32})'
                    source: log
                - labels:
                    trace_id:
                
                # タイムスタンプ抽出
                - timestamp:
                    source: timestamp
                    format: RFC3339Nano
              
              # ラベル付け（Kubernetesメタデータから）
              relabel_configs:
                # ポッド名
                - source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
                
                # Namespace
                - source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                
                # コンテナ名
                - source_labels:
                    - __meta_kubernetes_pod_container_name
                  target_label: container
                
                # アプリ名（ラベルから）
                - source_labels:
                    - __meta_kubernetes_pod_label_app
                  target_label: app
                
                # サービス名（ラベルから）
                - source_labels:
                    - __meta_kubernetes_pod_label_app_kubernetes_io_name
                  target_label: service
                
                # ノード名
                - source_labels:
                    - __meta_kubernetes_pod_node_name
                  target_label: node
                
                # ログパス
                - source_labels:
                    - __meta_kubernetes_pod_uid
                    - __meta_kubernetes_pod_container_name
                  target_label: __path__
                  separator: /
                  replacement: /var/log/pods/*$1/*.log
        
        # DaemonSet設定（全ノードで実行）
        daemonset:
          enabled: true
        
        # リソース設定
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        
        # ボリュームマウント
        # Helmチャートのデフォルトで以下がマウント済み:
        # - /var/log/pods (pods)
        # - /var/lib/docker/containers (containers) 
        # - /run/promtail (run, emptyDir)
        
        # ServiceMonitor（Prometheusで監視）
        serviceMonitor:
          enabled: true
          interval: 30s
          labels:
            release: kube-prometheus-stack
        
        # 優先度クラス
        priorityClassName: ""
        
        # Node Selector（特定ノードのみで実行する場合）
        nodeSelector: {}
        
        # Tolerations（全ノードで実行）
        tolerations:
          - effect: NoSchedule
            operator: Exists
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
