apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster

metadata:
  name: k0s-cluster-test
  user: admin

spec:
  hosts:
    - ssh:
        address: 192.168.11.240
        user: aoba
        port: 22
        keyPath: null
      role: controller

    - ssh:
        address: 192.168.11.241
        user: aoba
        port: 22
        keyPath: null
      role: worker

    - ssh:
        address: 192.168.11.242
        user: aoba
        port: 22
        keyPath: null
      role: worker

    - ssh:
        address: 192.168.11.243
        user: aoba
        port: 22
        keyPath: null
      role: worker
  # ====================
  # k0s Configuration
  # ====================
  k0s:
    version: null # Use the latest stable version
    config:
      # API server configuration
      apiServer:
        extraArgs:
          # Enable audit logging
          audit-log-maxage: 30
          audit-log-maxbackup: 3
          audit-log-maxsize: 100

      # Network configuration
      network:
        provider: calico # CNI plugin
        calico:
          mode: vxlan # or ipip
          vxlanPort: 4789
          mtu: 1450

      # Storage configuration  
      storage:
        type: etcd # embedded etcd

      # Enable pod security standards
      podSecurityPolicy:
        defaultPolicy: restricted
